version: '2'
services:
  web:
    build: .
    image: jritsema/demo:0.0.1
    ports:
      - "80:80"
    environment:
      PORT: 80
      DB_HOST: demo.cvnwc73rlm8x.us-east-1.rds.amazonaws.com
      DB_DATABASE: demo
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    labels: 
      kompose.service.expose: "true"
      kompose.service.type: loadbalancer      
